[build]
  command = "cd netlify/functions && npm install && cd ../.. && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.16.0"